# Generated by Django 6.0.4 on 2026-04-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rname', models.CharField(max_length=100)),
                ('rid', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='bname',
            field=models.CharField(max_length=100),
        ),
    ]
